### ISSUE TITLE
Update V1.1 problem

### ISSUE THREAD

**Issue by sam11fr** [humhub/humhub-modules-tasks#67] opened 2018-05-23 20:42 UTC
Hello.
After update V1.0.12 to V1.1, I have a problem with a missing task_item table.

LOG:
exception 'yii\base\InvalidConfigException' with message 'The table does not exist: task_item' in /protected/vendor/yiisoft/yii2/db/ActiveRecord.php:366 Stack trace: #0 /protected/vendor/yiisoft/yii2/db/ActiveRecord.php(210): yii\db\ActiveRecord::getTableSchema() #1 /protected/vendor/yiisoft/yii2/db/ActiveRecord.php(189): yii\db\ActiveRecord::filterCondition(Array) #2 /protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(116): yii\db\ActiveRecord::findByCondition(Array) #3 /protected/modules/tasks/models/Task.php(352): yii\db\BaseActiveRecord::findAll(Array) #4 /protected/vendor/yiisoft/yii2/db/ActiveRecord.php(675): humhub\modules\tasks\models\Task->beforeDelete() #5 /protected/vendor/yiisoft/yii2/db/ActiveRecord.php(646): yii\db\ActiveRecord->deleteInternal() #6 /protected/modules/tasks/Module.php(41): yii\db\ActiveRecord->delete() #7 /protected/humhub/components/ModuleManager.php(294): humhub\modules\tasks\Module->disable() #8 /protected/humhub/modules/admin/controllers/ModuleController.php(153): humhub\components\ModuleManager->removeModule('tasks') #9 [internal function]: humhub\modules\admin\controllers\ModuleController->actionRemove() #10 /protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #11 /www/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #12 /www/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('remove', Array) #13 /protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/module/re...', Array) #14 /www/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #15 /www/index.php(25): yii\base\Application->run() #16 {main} 

Humhub version 1.2.6
PHP 5.6.33
Task module not work.

Thank you.
Best regard

**Comment by sam11fr** [comment] 2018-05-24 19:35
Currently, the table 'tasks' contains twenty fields
- id
- title
- end_datetime
- max_users
- status
- created_at
-created_by
- updated_at
- updated_by
- color
- review
- description
- scheduling
- all_day
- start_datetime
- cal_mode
- time_zone
- request_sent
- task_list_id
- sort_order

**Comment by buddh4** [comment] 2018-05-25 14:17
which task_* related tables were created in your database?

**Comment by sam11fr** [comment] 2018-05-25 18:50
Only 2:
- task
- task_user

**Comment by steve-eubanks** [comment] 2018-05-26 14:49
I am having this same issue when updating the Tasks module.

Example of error when accessing Tasks in HumHub:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eubie02_ifi_fauxhawk.task_list_setting' doesn't exist
The SQL being executed was: SELECT `content_tag`.* FROM `content_tag` LEFT JOIN `task` ON task.task_list_id=content_tag.id LEFT JOIN `task_list_setting` ON task_list_setting.tag_id=content_tag.id WHERE (`content_tag`.`module_id`='tasks') AND (`content_tag`.`contentcontainer_id`=40) AND ((`task`.`status` IN (2, 3, 1)) OR (`task`.`id` IS NULL) OR (`task_list_setting`.`hide_if_completed`='0')) ORDER BY `task_list_setting`.`sort_order`
```
From Administration/Information/Database"

```
        Yii Migration Tool (based on Yii v2.0.12)

Total 4 new migrations to be applied:
	m180411_093623_checklist_and_revision
	m180502_142535_renameclasses
	m180504_092302_permission_name_and_list_updated_at
	m180515_120940_list_settings_updated_at

*** applying m180411_093623_checklist_and_revision
    > drop column percent from table task ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'percent'; check that column/key exists
The SQL being executed was: ALTER TABLE `task` DROP COLUMN `percent` (/var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/Schema.php:636)
#0 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/Command.php(852): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `ta...')
#1 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/Migration.php(362): yii\db\Command->execute()
#2 /var/www/ifi-fauxhawk/protected/modules/tasks/migrations/m180411_093623_checklist_and_revision.php(24): yii\db\Migration->dropColumn('task', 'percent')
#3 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/Migration.php(100): m180411_093623_checklist_and_revision->safeUp()
#4 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(671): yii\db\Migration->up()
#5 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(183): yii\console\controllers\BaseMigrateController->migrateUp('m180411_093623_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('up', Array)
#10 /var/www/ifi-fauxhawk/protected/humhub/commands/MigrateController.php(176): yii\console\Controller->runAction('up')
#11 /var/www/ifi-fauxhawk/protected/humhub/modules/admin/controllers/InformationController.php(76): humhub\commands\MigrateController::webMigrateAll()
#12 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#13 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#15 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('database', Array)
#16 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/informati...', Array)
#17 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#18 /var/www/ifi-fauxhawk/index.php(25): yii\base\Application->run()
#19 {main}
*** failed to apply m180411_093623_checklist_and_revision (time: 0.001s)


0 from 4 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

Task related tables in the database after update
- task
- task_item
- task_user

**Comment by steve-eubanks** [comment] 2018-05-26 15:11
For me, this problem has now gotten even worse.

I cannot disable the Tasks module for the site, I cannot disable it for a space, and I cannot uninstall it.

Here's what I get in the log after attempting to uninstall the module:
`yii\base\InvalidConfigException: The table does not exist: task_reminder in /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php:366 Stack trace: #0 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(210): yii\db\ActiveRecord::getTableSchema() #1 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(189): yii\db\ActiveRecord::filterCondition(Array) #2 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(116): yii\db\ActiveRecord::findByCondition(Array) #3 /var/www/ifi-fauxhawk/protected/modules/tasks/models/Task.php(360): yii\db\BaseActiveRecord::findAll(Array) #4 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(675): humhub\modules\tasks\models\Task->beforeDelete() #5 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(646): yii\db\ActiveRecord->deleteInternal() #6 /var/www/ifi-fauxhawk/protected/modules/tasks/Module.php(41): yii\db\ActiveRecord->delete() #7 /var/www/ifi-fauxhawk/protected/humhub/components/ModuleManager.php(294): humhub\modules\tasks\Module->disable() #8 /var/www/ifi-fauxhawk/protected/humhub/modules/admin/controllers/ModuleController.php(153): humhub\components\ModuleManager->removeModule('tasks') #9 [internal function]: humhub\modules\admin\controllers\ModuleController->actionRemove() #10 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #11 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #12 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('remove', Array) #13 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/module/re...', Array) #14 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #15 /var/www/ifi-fauxhawk/index.php(25): yii\base\Application->run() #16 {main}`

And here's what I get when I try to uninstall it from a space:
`yii\base\InvalidConfigException: The table does not exist: task_reminder in /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php:366 Stack trace: #0 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(210): yii\db\ActiveRecord::getTableSchema() #1 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(189): yii\db\ActiveRecord::filterCondition(Array) #2 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(116): yii\db\ActiveRecord::findByCondition(Array) #3 /var/www/ifi-fauxhawk/protected/modules/tasks/models/Task.php(360): yii\db\BaseActiveRecord::findAll(Array) #4 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(675): humhub\modules\tasks\models\Task->beforeDelete() #5 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(646): yii\db\ActiveRecord->deleteInternal() #6 /var/www/ifi-fauxhawk/protected/modules/tasks/Module.php(59): yii\db\ActiveRecord->delete() #7 /var/www/ifi-fauxhawk/protected/humhub/modules/space/behaviors/SpaceModelModules.php(171): humhub\modules\tasks\Module->disableContentContainer(Object(humhub\modules\space\models\Space)) #8 [internal function]: humhub\modules\space\behaviors\SpaceModelModules->disableModule('tasks') #9 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Component.php(287): call_user_func_array(Array, Array) #10 /var/www/ifi-fauxhawk/protected/humhub/modules/space/modules/manage/controllers/ModuleController.php(71): yii\base\Component->__call('disableModule', Array) #11 [internal function]: humhub\modules\space\modules\manage\controllers\ModuleController->actionDisable() #12 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #13 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #14 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('disable', Array) #15 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('space/manage/mo...', Array) #16 /var/www/ifi-fauxhawk/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #17 /var/www/ifi-fauxhawk/index.php(25): yii\base\Application->run() #18 {main}`

This is a problem, because now, not only does the Task module not work, but I cannot remove the offending module from my HumHub instance, so my users see it and think it's there, but only get errors when attempting to use it.

Please let me know if there is any additional testing I can do, or anything that will help to identify the cause and resolution of this issue.

Thanks!

**Comment by sam11fr** [comment] 2018-05-27 19:09
Hello,
it is urgent to solve this problem because it begins to have colaterals problems.
How to manually remove the task module ?
Delete files and tables task* ? Delete tasks entry in module_enabled table ?
I tried on a test server, obviously it works.
Best regards

**Comment by steve-eubanks** [comment] 2018-05-28 14:35
I have restored from backup my HumHub instance that was effected by this issue, and now get a different task related error: 
`Exception
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: humhub\modules\tasks\models\Task::deadline`

This error prevents my instance from loading at all.  So at this point, upgrading the task module has brought down my entire HumHub instance, and it will not load from backup.  If there is not a fix for this, please at least let people know that upgrading entails a risk to their instance.

**Comment by sam11fr** [comment] 2018-05-28 20:03
Hello,
so I manually removed the tasks module as explained above. I then ran a database integrity check (/protected/yii integrity/run) to fix the entries of tasks. I was also forced to rebuild the search engine index (/protected/yii search/rebuild).
Since then, the site is stable and operational again.

Please, inform customers of the potential risk to update this module.

Regards,
Sam11fr

**Comment by ouun** [comment] 2018-11-19 16:51
Same here. Even `yii module/disable tasks` returns `--- Modul deaktivieren: tasks ---Exception 'yii\base\InvalidConfigException' with message 'The table does not exist: task_item'`

**Closed** 2019-10-04 10:08 UTC
